### PR TITLE
Change SQL API from mysql to mysqli to support PHP7 on Ubuntu 16.04

### PR DESCRIPTION
**Pull request by jomaxro**
Ubuntu 16.04 provides PHP 7.0, where Ubuntu 14.04 and Ubuntu 12.04 came with PHP 5.x.

PHP 5.x supports 3 MySQL APIs: `ext/mysql`, `ext/mysqli`, and `PDO_MySQL`, where PHP 7.0 drops support for `ext/mysql`.  RPI_QuickLogs uses `ext/mysql` and therefore is incompatible with Unbuntu 16.04 and PHP 7.0.

These commits change the MySQL API for RPI_QuickLogs to `ext/mysqli` to support running on Ubuntu 16.04.

### CODE REVIEW

**Comment by daberkow** [comment]
Ello! Nice to see someone working on this and that it appears to still be in use. Im happy to accept your changes, but without a setup instance, I am going to have to trust you tested this. :)

**Comment by jomaxro** [comment]
It sure is still in use!  We've made some very minor changes over the last few years - removed the debouncing code as it is no longer an issue with current touch screens, required authorization so it is known who is logging what (not default), and now this change.

It was tested here on leet (which is no longer on the back desk - we've been virtualized down in operations!).  I can't say whether the changes are backwards compatible with earlier versions of PHP (<7), but looking at the documentation it should still work.

**Comment by daberkow** [comment]
Cool, are you going to be maintaining in the future?

**Comment by jomaxro** [comment]
No 😞.  I just graduated but was working on getting the server as up-to-date as possible before I leave at the end of this week.  You wrote a great application, Quicklogs hasn't "needed" any changes other than this before.  All previous changes were by choice (forcing auth, remove debounce).  The goal with this update (and other update's we've done) is that nothing should need to be touched for another few years.

**Comment by daberkow** [comment]
Ah! Well congrats on graduating! I good luck on future endeavors! If anyone wants to commit, or in the future maintain I am happy to add them as a admin on the repo.

**Pull request merged**
